import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import {
  buildComponentItem,
  buildHookItem,
  buildIndex,
  buildThemeItem,
  buildUtilItem,
  scanComponents,
} from './lib/registry';

const ROOT = join(import.meta.dirname, '..');
const COMPONENTS_DIR = join(ROOT, 'src', 'components');
const UTILS_DIR = join(ROOT, 'src', 'utils');
const HOOKS_DIR = join(ROOT, 'src', 'hooks');
const THEME_CSS = join(ROOT, 'src', 'styles', 'theme.css');
const OUTPUT_DIR = join(ROOT, 'registry');
const JSON_DIR = join(OUTPUT_DIR, 'json');

const HOMEPAGE =
  process.env.REGISTRY_HOMEPAGE ??
  (process.env.VERCEL_PROJECT_PRODUCTION_URL
    ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`
    : 'http://localhost:3000');

const components = scanComponents(COMPONENTS_DIR);

/** Source `.ts` modules in a flat dir, excluding tests and barrels. */
const sourceModules = (dir: string, exclude: string[] = []) =>
  readdirSync(dir).filter(
    (file) =>
      file.endsWith('.ts') &&
      !file.endsWith('.spec.ts') &&
      file !== 'index.ts' &&
      !exclude.includes(file)
  );

// Internal utils (except cn — consumers get that from the shadcn `utils` item)
// each become a registry:lib item, e.g. /r/format.json → lib/format.ts.
const utilItems = sourceModules(UTILS_DIR, ['cn.ts']).map((file) =>
  buildUtilItem(basename(file, '.ts'), readFileSync(join(UTILS_DIR, file), 'utf-8'))
);

// Each hook (src/hooks/use-*.ts) becomes a registry:hook item,
// e.g. /r/use-clipboard.json → hooks/use-clipboard.ts.
const hookItems = sourceModules(HOOKS_DIR).map((file) =>
  buildHookItem(basename(file, '.ts'), readFileSync(join(HOOKS_DIR, file), 'utf-8'))
);

const items = [
  ...components.map(buildComponentItem),
  ...utilItems,
  ...hookItems,
  buildThemeItem(readFileSync(THEME_CSS, 'utf-8')),
];
const index = buildIndex(items, HOMEPAGE);

rmSync(OUTPUT_DIR, { recursive: true, force: true });
mkdirSync(JSON_DIR, { recursive: true });

for (const item of items) {
  writeFileSync(join(JSON_DIR, `${item.name}.json`), JSON.stringify(item, null, 2));
}
writeFileSync(join(JSON_DIR, 'index.json'), JSON.stringify(index, null, 2));

// Emit a TypeScript module so the Vercel function (api/r/[name].ts) gets the
// registry statically bundled — no runtime fs access or includeFiles config.
const moduleSource = `// AUTO-GENERATED by scripts/build-registry.ts — do not edit.
import type { RegistryIndex, RegistryItem } from '../scripts/lib/registry-types';

export const registryIndex: RegistryIndex = ${JSON.stringify(index, null, 2)};

export const registryItems: Record<string, RegistryItem> = ${JSON.stringify(
  Object.fromEntries(items.map((item) => [item.name, item])),
  null,
  2
)};
`;
writeFileSync(join(OUTPUT_DIR, 'items.ts'), moduleSource);

console.log(
  `Registry built: ${items.length} items → registry/json/ and registry/items.ts`
);
