import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  buildComponentItem,
  buildIndex,
  buildThemeItem,
  scanComponents,
} from './lib/registry';

const ROOT = join(import.meta.dirname, '..');
const COMPONENTS_DIR = join(ROOT, 'src', 'components');
const THEME_CSS = join(ROOT, 'src', 'styles', 'theme.css');
const OUTPUT_DIR = join(ROOT, 'registry');
const JSON_DIR = join(OUTPUT_DIR, 'json');

const HOMEPAGE =
  process.env.REGISTRY_HOMEPAGE ??
  (process.env.VERCEL_PROJECT_PRODUCTION_URL
    ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`
    : 'http://localhost:3000');

const components = scanComponents(COMPONENTS_DIR);
const items = [
  ...components.map(buildComponentItem),
  buildThemeItem(readFileSync(THEME_CSS, 'utf-8')),
];
const index = buildIndex(items, HOMEPAGE);

rmSync(OUTPUT_DIR, { recursive: true, force: true });
mkdirSync(JSON_DIR, { recursive: true });

for (const item of items) {
  writeFileSync(join(JSON_DIR, `${item.name}.json`), JSON.stringify(item, null, 2));
}
writeFileSync(join(JSON_DIR, 'index.json'), JSON.stringify(index, null, 2));

// Emit a TypeScript module so the Vercel function (api/r/[name].ts) gets the
// registry statically bundled — no runtime fs access or includeFiles config.
const moduleSource = `// AUTO-GENERATED by scripts/build-registry.ts — do not edit.
import type { RegistryIndex, RegistryItem } from '../scripts/lib/registry-types';

export const registryIndex: RegistryIndex = ${JSON.stringify(index, null, 2)};

export const registryItems: Record<string, RegistryItem> = ${JSON.stringify(
  Object.fromEntries(items.map((item) => [item.name, item])),
  null,
  2
)};
`;
writeFileSync(join(OUTPUT_DIR, 'items.ts'), moduleSource);

console.log(
  `Registry built: ${items.length} items → registry/json/ and registry/items.ts`
);
